### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by jackietom** [feichtenhofer/gpu_flow#7]
I have set the vidpath, out_path and out_path_jpeg in compute_flow.cpp and builded it. However, when I ran build/comput_flow, it only print "start_vid:1gpuID:1flow method: 1 frameSkip: 1
Device 1:  "GeForce GTX 1080 Ti"  11172Mb, sm_61, Driver/Runtime ver.9.0/8.0" and ended.

Is there anyone know what's up?

**Comment by laura-wang** [comment]
hello, @jackietom , do you know how to solve it? I have the same problem here

**Comment by DoubleYing** [comment]
hello, @jackietom , do you know how to solve it? I have the same problem here
